name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      APP_URL: "http://127.0.0.1:8000"
      DB_CONNECTION: mysql
      DB_DATABASE: testing
      DB_HOST: 127.0.0.1
      DB_PASSWORD: password
      DB_PORT: 33306
      DB_USERNAME: root
      DUSK_DRIVER_URL: "http://selenium:4444"
      LARAVEL_DUSK: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Configure environment
        run: |
          cp ./.env.example ./.env
          rm ./.env.dusk.local
          chmod -R 777 ./storage ./bootstrap/cache
          
      - name: Build frontend
        run: |
          npm install
          npm run build

      - name: Composer install
        run: |
          composer install

      - name: Generate application key
        run: |
          php artisan key:generate

      - name: Run migrations
        run: |
          php artisan migrate

      - name: Publish assets
        run: |
          php artisan vendor:publish --tag backend

      - name: Application tests
        run: |
          php artisan test

      - name: Install Chrome
        run: |
          php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`

      - name: Start Chrome
        run: |
          ./vendor/laravel/dusk/bin/chromedriver-linux &
      
      - name: Browser tests
        run: |
          php artisan serve --no-reload --quiet &
          php artisan dusk

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console

      - name: Upload Source Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: source
          path: tests/Browser/source